apiVersion: v1
kind: ConfigMap
metadata:
  name: commx-config
  namespace: commx
  labels: 
    app.kubernetes.io/name: commx-config
    app.kubernetes.io/part-of: commx
data:
  NODE_ENV: "production"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PORT: "3000"
