apiVersion: v1
kind: Secret
metadata:
  name: commx-secret
  namespace: commx
  labels:
    app.kubernetes.io/name: commx-secret
    app.kubernetes.io/part-of: commx
type: Opaque
stringData:
  POSTGRES_USER: "user_db"
  POSTGRES_PASSWORD: "pass_db"
  POSTGRES_DB: "commx_db"

  DATABASE_URL: "postgresql://user_db:pass_db@postgres.commx.svc.cluster.local:5432/commx_db"

