apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: commx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://192.168.2.5:3000/prk/tpaonsite.git'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: commx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
